# Generated by Django 3.2.15 on 2022-08-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoauthapi1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
